### ISSUE TITLE
Leftover conflict in the LICENSE

### ISSUE THREAD

**Issue by nevali** [lzfse/lzfse#13]
The `LICENSE` file in its current form is in a conflicted state (`HEAD` vs `a7fa1f9dd645a3937217f51b2052221eeadeae45`).

It looks by eye to be just formatting changes, but I can't be sure without a proper comparison, and given the importance of the document it's probably worth resolving as soon as possible!

**Comment by ebainville** [comment]
Thanks. Fixed in #12
