### ISSUE TITLE
License and Usage Approval Questions

### ISSUE THREAD

**Issue by cookiengineer** [lzfse/lzfse#16]
So far LZFSE seems to be quite nice as an alternative to zlib. But I hope that I'm not the only one having troubles using a proprietary copyrighted algorithm which might deny me to use this software piece in future.

My questions so far are:

1) Will there be an RFC for LZFSE or any intention to standardize this algorithm to the public so that cross-platform adaption is possible?
2) Will LZFSE be distributed via another License (like Apache, BSD or MIT)?
3) What kind of patents by Apple are involved in the usage and adaption of LZFSE?

Thanks in advice.

**Comment by ebainville** [comment]
This repository contains a reference implementation of LZFSE, precisely to allow cross-platform adoption. The code is distributed under a BSD license.

Issues not related to features/bugs in the software itself are off-topic.

**Comment by ebainville** [comment]
Please close this issue if your question has been answered.

**Comment by nemequ** [comment]
I don't care about (1) ("no", or "nothing is currently planned" are completely fine with me), but I'm definitely interested in an answer to (3), especially given that Apple has used patents offensively in the past…

Something like [what Google did for Brotli](https://datatracker.ietf.org/ipr/2396/) would be okay, or maybe a patent license grant along the lines of part 3 of the Apache 2.0 license or what the alliance for open media is doing.

**Comment by cookiengineer** [comment]
@ebainville I don't know, but as there's no other official contact that seems to be responsible; I think this question is essential for the sake of survival of this project. ~~If the license stays the way it is shipped, there's literally no use case for LZFSE.~~ Sorry, my bad. BSD style license is superb!

**Comment by nemequ** [comment]
The license is a [3-clause BSD license](https://opensource.org/licenses/BSD-3-Clause), what's wrong with that?  It's a very popular OSI-approved open-source license.

**Comment by cookiengineer** [comment]
Sorry, haven't seen the formatted license two days ago. Issue can be closed, everything okay :+1:

**Comment by nemequ** [comment]
@ebainville, I'm still interested in the patent issue… should I open up a separate issue for that, or just abandon all hope?

**Comment by ebainville** [comment]
@nemequ yes, you can create a separate issue. Thanks.
