### ISSUE TITLE
Clarify patent situation

### ISSUE THREAD

**Issue by nemequ** [lzfse/lzfse#21]
I would appreciate some sort of clarification on LZFSE's patent situation.  At minimum, if Apple believes it has any patents relevant to LZFSE they should disclose them, and if Apple doesn't have any relevant patents it should provide a statement to that effect (Google recently did [something similar](https://datatracker.ietf.org/ipr/2396/) for Brotli).

Ideally, though, I would like to see some sort of patent license grant for any patents it owns or acquires which read on LZFSE, at least for the purpose of using LZFSE.

**Comment by ebainville** [comment]
**Apple does not hold any patents that cover LZFSE technology.**

**Comment by nemequ** [comment]
Thanks; I know this was probably a PITA to sort out with legal, but I really appreciate it.
