### ISSUE TITLE
Library release versioning

### ISSUE THREAD

**Issue by rmax** [lzfse/lzfse#39]
Hi, I noticed the project doesn't have proper releases and that makes hard to build package for third party distribution.

In particular, I was adding the package for this library to [conda-forge](https://conda-forge.github.io/) (see https://github.com/conda-forge/staged-recipes/pull/2596) and having versions somewhat required. It would be posible to have tags (and optionally releases) that we can refer to?

CC @jakirkham

**Comment by jakirkham** [comment]
Friendly nudge. 😉 Would really like to make this accessible to more people by packaging it, but not having some kind of release makes that difficult. Any chance we can get a tag?

**Comment by ebainville** [comment]
I tagged the current master lzfse-1.0.
Thanks for reminding me.

**Comment by jakirkham** [comment]
Awesome. Thanks @ebainville. 😄

**Comment by jakirkham** [comment]
FYI the [feedstock]( https://github.com/conda-forge/lzfse-feedstock ) for `lzfse` is in [conda-forge]( http://conda-forge.github.io/ ) with [packages]( https://anaconda.org/conda-forge/lzfse ) on Anaconda.org installable on Mac, Linux, and Windows with the [conda]( https://conda.io/docs/ ) package manager.
