### ISSUE TITLE
MSVC support

### ISSUE THREAD

**Issue by nemequ** [lzfse/lzfse#8]
LZFSE currently fails to build with MSVC.  See https://ci.appveyor.com/project/quixdb/squash/build/470/job/1fvyqd3lrkrpem6t#L1388 for a build log.

@jibsen kindly [looked into this](http://encode.ru/threads/2221-LZFSE-New-Apple-Data-Compression?p=48487&viewfull=1#post48487), and it seems the major issue is reliance on [a gcc extension](https://gcc.gnu.org/onlinedocs/gcc/Labels-as-Values.html) in lzvn_decode_base.c.

**Comment by jibsen** [comment]
I think I've got lzfse working with MSVC, I'll clean up the changes a bit later.

**Comment by jibsen** [comment]
Okay, the MSVC fixes are up at https://github.com/jibsen/lzfse/tree/msvc-compatibility

If there is any interest in this, let me know and I will open a PR.

jibsen/lzfse@9037b59 and jibsen/lzfse@a2211c5 are just general fixes and should probably be brought in regardless.

**Comment by nemequ** [comment]
This would likely make it easier to get LZFSE working with other compilers, too.  I just tested with Oracle Solaris Studio 12.4 a few minutes ago and it failed, but I'd rather base changes on this branch than master…

**Comment by nemequ** [comment]
@ebainville any thoughts on this?  I was thinking about getting LZFSE working on big endian, but if you don't care about portability I probably won't bother…

**Comment by ebainville** [comment]
@jibsen Yes, please can you rebase the changes to the current master, and create a PR?
@nemequ Evan, I'll soon have some time to work on the open issues.

**Comment by ebainville** [comment]
Merged with pull request #27
